# Generated by Django 2.2.6 on 2019-12-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('inputEmail', models.CharField(max_length=250)),
                ('phoneNumber', models.BigIntegerField(max_length=250)),
                ('dateOfBirth', models.DateField(max_length=250)),
                ('locationCriteria', models.CharField(max_length=250)),
                ('eventCategories', models.CharField(max_length=250)),
            ],
        ),
    ]