# Generated by Django 2.2.6 on 2019-12-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20191201_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='dateOfBirth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
