# Generated by Django 2.2.6 on 2019-12-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_profileinfo_userpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='eventCategories',
            field=models.CharField(choices=[('1', 'Books'), ('2', 'Sports'), ('3', 'Learning'), ('4', 'Travel'), ('5', 'Technical'), ('6', 'Music')], max_length=250),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='locationCriteria',
            field=models.CharField(choices=[('Starbucks', 'Starbucks'), ('Recess Coffee', 'Recess Coffee'), ('Dunkin Donuts', 'Dunkin Donuts'), ('Dorians', 'Dorians'), ('Alto Cinco', 'Alto Cinco'), ('Pages Cafe', 'Pages Cafe')], max_length=250),
        ),
    ]
