# Generated by Django 2.2.6 on 2019-12-02 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20191202_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
