# Generated by Django 2.2.6 on 2019-12-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_eventinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
