# Generated by Django 2.2.6 on 2019-12-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_auto_20191202_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='slug',
        ),
    ]
