# Generated by Django 2.2.6 on 2019-12-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_remove_eventinfo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
