# Generated by Django 2.2.6 on 2019-12-03 23:59

from django.db import migrations

import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_eventinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='EventLocation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cafe_1', 'Starbucks'), ('cafe_2 ', 'Dunkin Donuts'), ('cafe_3', 'Recess'), ('cafe_4', 'Alto Chinco'), ('cafe_5', 'Gangnam Style')], max_length=35),
        ),
    ]
    
