# Generated by Django 2.2.6 on 2019-12-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0011_auto_20191203_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='slug',
        ),
    ]
