# Generated by Django 2.2.6 on 2019-12-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_auto_20191204_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='OwnerId',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
