# Generated by Django 2.2.6 on 2019-12-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0014_eventinfo_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='OwnerId',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
