# Generated by Django 2.2.6 on 2019-12-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0016_eventinfo_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='EventLocation',
            field=models.CharField(max_length=100),
        ),
    ]
