# Generated by Django 2.2.6 on 2019-12-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0018_eventinfo_isinitialized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='NoofAttendees',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
