# Generated by Django 2.2.6 on 2019-12-17 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0020_auto_20191217_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='EventLocation',
            field=models.ForeignKey(db_column='EventLocation', on_delete=django.db.models.deletion.CASCADE, to='NearbyEvents.LocationPreferences'),
        ),
    ]
