# Generated by Django 2.2.6 on 2019-12-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafeName', models.CharField(max_length=255)),
                ('EventAddress', models.CharField(max_length=500)),
                ('CafeContact', models.BigIntegerField()),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
        ),
    ]
